### ISSUE TITLE
The page is always loading.

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [bookchris/bridge-dds-js#3]
The page is always loading. Could you kindly provide a way to run this?

**Comment by bookchris** [comment]
I've been meaning to get back to this.  I may have a more polished version locally I can push.

Let me look later.

**Comment by bookchris** [comment]
I believe I fixed it.  The example code was pointing to an older version.  Seems to be working now with this:
https://github.com/bookchris/bridge-dds-js/pull/4

**Comment by S-N-O-R-L-A-X** [comment]
Looks good, it isn't loading anymore. Thanks.
